replicaCount: 2
image:
  repository: europe-west1-docker.pkg.dev/teak-advice-475415-i2/petclinic-repo-dev/petclinic
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  host: "petclinic.internal" # You can map this in your /etc/hosts later to test

googleProjectId: "teak-advice-475415-i2" # Update this or pass it via --set

cloudSql:
  # Connection name format: project:region:instance
  instanceConnectionName: "teak-advice-475415-i2:europe-west1:petclinic-db-dev"