# chart/petclinic/values-prod.yaml

replicaCount: 2

cloudSql:
  instanceConnectionName: "teak-advice-475415-i2:europe-west1:petclinic-db-prod"

serviceAccount:
  gcpEmail: "petclinic-sa-prod@teak-advice-475415-i2.iam.gserviceaccount.com"

ingress:
  enabled: true
  host: "petclinic.internal"

image:
  repository: "europe-west1-docker.pkg.dev/teak-advice-475415-i2/petclinic-repo-prod/petclinic"

googleProjectId: "teak-advice-475415-i2"
environment: "prod"