# chart/petclinic/values.yaml

# 1. Scaling Defaults
replicaCount: 1

# 2. Image Configuration
image:
  repository: "gcr.io/google-samples/hello-app" # Placeholder
  pullPolicy: IfNotPresent
  tag: ""

# 3. Application Config
cloudSql:
  instanceConnectionName: ""

# 4. Service Account
serviceAccount:
  create: true
  gcpEmail: "" 

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: "nginx"
  host: "localhost"
  
resources: {}