replicaCount: 1

cloudSql:
  instanceConnectionName: "teak-advice-475415-i2:europe-west1:petclinic-db-dev"

serviceAccount:
  gcpEmail: "petclinic-sa-dev@teak-advice-475415-i2.iam.gserviceaccount.com"

ingress:
  enabled: true
  className: "nginx"
  host: "dev.petclinic.internal"
  
image:
  repository: "europe-west1-docker.pkg.dev/teak-advice-475415-i2/petclinic-repo-dev/petclinic"

googleProjectId: "teak-advice-475415-i2"
environment: "dev"
