name: Application Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJECT_ID: "teak-advice-475415-i2"
  REGION: "europe-west1"
  REPO_NAME: "petclinic-repo-dev"
  IMAGE_NAME: "petclinic"

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: ./mvnw test

      - name: Build Package
        run: ./mvnw clean package -DskipTests

      - name: Prepare Docker Files
        run: |
          # 1. Move and rename the App JAR
          mv target/*.jar spring-petclinic.jar
          
          # 2. Download the Prometheus JMX Agent
          curl -L https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.20.0/jmx_prometheus_javaagent-0.20.0.jar -o jmx.jar
          
          # 3. Verify all files exist before building
          ls -l spring-petclinic.jar jmx.jar config.yaml

      - name: Configure Docker Auth
        run: |
          # This registers the gcloud credential helper for your specific registry region
          gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Build and Push Image
        run: |
          IMAGE_URI="$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:${{ github.sha }}"
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Build and Push Image
        run: |
          IMAGE_URI="$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:${{ github.sha }}"
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Deploy with Helm
        run: |
          gcloud container clusters get-credentials petclinic-gke-dev --region europe-west1 --project teak-advice-475415-i2
          
          helm upgrade --install petclinic ./chart/petclinic \
            --set image.repository="$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME" \
            --set image.tag=${{ github.sha }} \
            --wait