apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Chart.Name }}-secrets
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.googleProjectId }}/secrets/petclinic-db-username/versions/latest"
        path: "spring.datasource.username"  # <-- filename matches property name
      - resourceName: "projects/{{ .Values.googleProjectId }}/secrets/petclinic-db-password/versions/latest"
        path: "spring.datasource.password"  # <-- filename matches property name
      - resourceName: "projects/{{ .Values.googleProjectId }}/secrets/petclinic-db-url/versions/latest"
        path: "spring.datasource.url"       # <-- filename matches property name