apiVersion: v1
kind: ServiceAccount
metadata:
  name: petclinic-sa
  annotations:
    # This annotation tells GKE to use the Google Service Account we created in Terraform
    iam.gke.io/gcp-service-account: petclinic-app-sa@{{ .Values.googleProjectId }}.iam.gserviceaccount.com