apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "petclinic.fullname" . }}
  labels:
    release: prometheus-community
    {{- include "petclinic.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "petclinic.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http-web
      path: /actuator/prometheus
      interval: 15s